"""Document and slide generation using LLM outputs."""

from __future__ import annotations

from pathlib import Path
from typing import List

from docx import Document
from pptx import Presentation


def write_docx(title: str, sections: List[str], output_path: Path) -> None:
    doc = Document()
    doc.add_heading(title, level=1)
    for section in sections:
        doc.add_paragraph(section)
    doc.save(output_path)


def write_pptx(title: str, slides: List[str], output_path: Path) -> None:
    prs = Presentation()
    title_slide = prs.slides.add_slide(prs.slide_layouts[0])
    title_slide.shapes.title.text = title
    if title_slide.placeholders and len(title_slide.placeholders) > 1:
        title_slide.placeholders[1].text = "Generated by KT.ai"
    for slide_text in slides:
        slide = prs.slides.add_slide(prs.slide_layouts[1])
        slide.shapes.title.text = title
        body = slide.shapes.placeholders[1].text_frame
        for line in slide_text.split("\n"):
            if line.strip():
                body.add_paragraph().text = line.strip()
    prs.save(output_path)
